on:
  push:
   branches:
    - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
     - id: checkout
       uses: actions/checkout@v3

     - id: install-and-build
       uses: actions/setup-node@v3
       with:
         node-version: 18
     - run: npm ci
     - run: npm run build

     - id: publish
       uses: bitovi/github-actions-react-to-ghp@v1.2.0
       with:
        path: dist
