name: Build and publish page

on:
  push:
    branches: [ "main", "gh-pages" ]
  pull_request:
    branches: [ "main", "gh-pages" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2.5.0
    - name: Setup Node.JS 19.x
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 19.x
    - name: Build
      run: |
        yarn install
        yarn run build


  deploy:
   needs: build
   environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
   runs-on: ubuntu-latest
   steps:
    - name: Setup Pages
      id: setup-pages
      uses: actions/configure-pages@v2.1.3
    - name: Upload Artifact
      id: upload-artifact
      uses: actions:/upload-pages-artifact@v1.0.5
      with:
       path: './dist'
    - name: Deploy to GH Pages
      id: deploy
      uses: actions/deploy-pages@v1.2.3
