name: Build and publish page

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - scripts/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        id: checkout-branch
        uses: actions/checkout@v3

      - name: Setup Node.JS 20.x
        id: setup-node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20.x

      - name: Build
        id: build
        run: |
          yarn install && yarn run build

      - name: Setup Pages
        id: setup-pages
        uses: actions/configure-pages@main

      - name: Upload Artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: dist

      - name: Deploy to GH Pages
        id: deploy
        uses: actions/deploy-pages@main
